#!/usr/bin/env sh

coords=$(./region)
set -- $coords

X=$1
Y=$2
W=$3
H=$4

# retina scaling
SCALE=2
X=$((X * SCALE))
Y=$((Y * SCALE))
W=$((W * SCALE))
H=$((H * SCALE))


# read -r X Y W H < <(./region)

SCREEN_H=1800 # adjust or detect dynamically
Y=$((SCREEN_H - Y - H))

ffmpeg \
    -f avfoundation \
    -framerate 30 \
    -i "1:none" \
    -vf "crop=${W}:${H}:${X}:${Y}" \
    -pix_fmt yuv420p \
    out.mp4
