---
name: Build & Release
on:
    release:
        types: [created]
permissions:
    contents: write
jobs:
    build:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set version
              id: vars
              run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            - name: Build arm64
              run: |
                swiftc -O -target arm64-apple-macos11.0 src/*.swift -o rgn-arm64
            - name: Build x86_64
              run: |
                swiftc -O -target x86_64-apple-macos11.0 src/*.swift -o rgn-x86_64
            - run: strip rgn
            - name: Package arm64
              run: |
                mkdir -p dist/arm64
                mv rgn dist/arm64/
                tar -czf rgn-${{ steps.vars.outputs.VERSION }}-darwin_arm64.tar.gz -C dist/arm64 rgn
            - name: Package x86_64
              run: |
                mkdir -p dist/amd64
                mv rgn dist/amd64/
                tar -czf rgn-${{ steps.vars.outputs.VERSION }}-darwin_amd64.tar.gz -C dist/amd64 rgn
            - name: Upload release assets
              uses: softprops/action-gh-release@v2
              with:
                files: |
                    rgn-*-darwin_*.tar.gz
